Review and update find command
AY2425S1-CS2103-F10-3/tp pull request #146
Opened 2024-10-13 06:36 UTC by KennethTeo2002

Implement partial name search

2024-10-13 06:42 UTC, sheenkerr requested changes

2024-10-13 06:42 UTC, sheenkerr commented on docs/DeveloperGuide.md
> +1.  Actor requests to find specific people.
Maybe can add an extension for no person found?

2024-10-13 14:02 UTC, sheenkerr submitted a review, later dismissed
LGTM

2024-10-15 15:49 UTC, joeltio approved these changes
LGTM

2024-10-15 16:26 UTC, ITLimJiaWei approved these changes
LGTM

2024-10-15 16:31 UTC, merged