Add details GUI Page
AY2425S1-CS2103-F10-3/tp pull request #147
Opened 2024-10-13 11:10 UTC by sheenkerr

Closes #131

2024-10-13 12:46 UTC, Nicholas-Cheng-De-Fei requested changes
In my opinion it might be better to clear the screen if I were to delete a contact that I have clicked

For example if I click on person 1 and I delete them afterwards the side panel should be empty.

But now when I delete a selected person, their details are still on screen

2024-10-13 12:52 UTC, Nicholas-Cheng-De-Fei requested changes

2024-10-13 12:52 UTC, Nicholas-Cheng-De-Fei commented on src/main/java/seedu/address/ui/PersonDetails.java
> +            notes.setStyle("-fx-text-fill: white;");
I think it is better to put the styling in the .fxml file instead of setting it here

2024-10-13 12:52 UTC, Nicholas-Cheng-De-Fei commented on src/main/java/seedu/address/ui/PersonDetails.java
> +            nameLabel.setStyle("-fx-text-fill: white;");
Same as what I mentioned previously

2024-10-14 06:52 UTC, ITLimJiaWei approved these changes
LGTM pending changes recommended by Nicholas and trailing white space removal

2024-10-14 06:52 UTC, ITLimJiaWei commented on src/main/java/seedu/address/ui/PersonDetails.java
> +
Trailing whitespace can be removed

2024-10-14 13:18 UTC, Nicholas-Cheng-De-Fei approved these changes
LGTM

2024-10-14 13:29 UTC, merged