Update UG & DG to include addnotes command and updated class diagrams for view command
AY2425S1-CS2103-F10-3/tp pull request #164
Opened 2024-10-15 16:56 UTC by sheenkerr

Closes #134 & #163

2024-10-15 17:03 UTC, Nicholas-Cheng-De-Fei requested changes

2024-10-15 17:03 UTC, Nicholas-Cheng-De-Fei commented on docs/DeveloperGuide.md
> +      Use case ends.
I think you forgot to change the use case for adding notes?

2024-10-15 17:04 UTC, ITLimJiaWei requested changes
Extension and small grammar mistake as mentioned

2024-10-15 17:04 UTC, ITLimJiaWei commented on docs/DeveloperGuide.md
> +- 2a. The specified person is invalid.
This extension should start at 3a as mentioned in tutorial

2024-10-15 17:04 UTC, ITLimJiaWei commented on docs/DeveloperGuide.md
> +- 2b. The note name is invalid.
Same as above but 3b

2024-10-15 17:04 UTC, ITLimJiaWei commented on docs/DeveloperGuide.md
> +2.  Actor request to add a note to a specific person.
Small grammar mistake, requests*

2024-10-15 17:21 UTC, Nicholas-Cheng-De-Fei requested changes

2024-10-16 01:58 UTC, Nicholas-Cheng-De-Fei requested changes

2024-10-16 01:58 UTC, Nicholas-Cheng-De-Fei commented on docs/DeveloperGuide.md
> +1.  Actor performs <u>list all people (UC2)</u>.
Can double check do we actually need this line since our application the user will never need to list all people?

2024-10-16 01:58 UTC, Nicholas-Cheng-De-Fei commented on docs/UserGuide.md
> +
Indicate that `INDEX` must be positive and within the range of the list like in the `delete` section above

2024-10-16 07:35 UTC, ITLimJiaWei approved these changes
LGTM

2024-10-16 08:16 UTC, Nicholas-Cheng-De-Fei approved these changes
LGTM

2024-10-16 08:19 UTC, merged