Edit notes command
AY2425S1-CS2103-F10-3/tp pull request #212
Opened 2024-10-23 07:36 UTC by sheenkerr

Closes #183 

Used editnotes as command word to follow the addnotes syntax.

2024-10-23 14:59 UTC, Nicholas-Cheng-De-Fei requested changes

2024-10-23 14:59 UTC, Nicholas-Cheng-De-Fei commented on src/main/java/seedu/address/logic/commands/EditNotesCommand.java
One bug I found was that the `ContactDetails` panel does not get updated after I edited the notes of a person.

2024-10-23 14:59 UTC, Nicholas-Cheng-De-Fei commented on src/main/java/seedu/address/logic/parser/AddressBookParser.java
> +        case EditNotesCommand.COMMAND_WORD:
Add a line spacing above

2024-10-24 04:00 UTC, Nicholas-Cheng-De-Fei requested changes

2024-10-24 14:01 UTC, Nicholas-Cheng-De-Fei commented on src/main/java/seedu/address/logic/commands/EditNotesCommand.java
Move bug fix to v1.5

2024-10-24 14:04 UTC, Nicholas-Cheng-De-Fei approved these changes
LGTM

2024-10-24 14:21 UTC, ITLimJiaWei approved these changes
Very minor formatting issues but overall LGTM

2024-10-24 14:21 UTC, ITLimJiaWei commented on src/test/java/seedu/address/testutil/TypicalNotes.java
> +
Small formatting issue of blank space here

2024-10-24 14:21 UTC, ITLimJiaWei commented on src/test/java/seedu/address/logic/commands/EditNotesCommandTest.java
> +                TYPICAL_NOTE.getNote(), "Likes dumplings").build();
Better to have "Likes dumplings" defined as a final static var elsewhere but minor issue.

2024-10-24 14:21 UTC, ITLimJiaWei commented on src/test/java/seedu/address/testutil/TypicalIndexes.java
> +
Extra empty space here

2024-10-24 14:22 UTC, merged