Implement unpin function
AY2425S1-CS2103-F10-3/tp pull request #232
Opened 2024-10-26 15:47 UTC by KennethTeo2002

Closes #201

2024-10-31 09:16 UTC, ITLimJiaWei approved these changes
LGTM with very minor comment adjustment in a equals testing

2024-11-02 06:08 UTC, Nicholas-Cheng-De-Fei approved these changes
LGTM

2024-11-02 06:19 UTC, Nicholas-Cheng-De-Fei requested changes

2024-11-02 06:19 UTC, Nicholas-Cheng-De-Fei commented on src/main/java/bizbook/logic/commands/UnpinCommand.java
I think need to update the delete command to also unpin if it deletes a contact that is pinned

2024-11-02 06:57 UTC, Nicholas-Cheng-De-Fei approved these changes
LGTM

2024-11-02 06:58 UTC, merged