Add unit tests for delete notes and add notes command parser
AY2425S1-CS2103-F10-3/tp pull request #249
Opened 2024-10-31 06:59 UTC by ITLimJiaWei

Closes #243

2024-11-04 16:23 UTC, Nicholas-Cheng-De-Fei requested changes

2024-11-04 16:23 UTC, Nicholas-Cheng-De-Fei commented on src/test/java/bizbook/logic/commands/DeleteNotesCommandTest.java
> +        Index validNoteIndex = Index.fromOneBased(1);
I think this one you should add it as the `INDEX_FIRST_PERSON` as what was done in the line above for reusability.

So like the first person for the test address book will have 2 notes

2024-11-04 16:23 UTC, Nicholas-Cheng-De-Fei commented on src/test/java/bizbook/logic/commands/DeleteNotesCommandTest.java
> +        Index noteIndexSecond = Index.fromOneBased(2);
Same as what was mentioned above

2024-11-05 10:03 UTC, Nicholas-Cheng-De-Fei approved these changes
LGTM

2024-11-05 10:33 UTC, sheenkerr approved these changes
LGTM

2024-11-05 10:33 UTC, merged