Add visuals in UG
AY2425S1-CS2103-F10-3/tp pull request #380
Opened 2024-11-10 05:37 UTC by Nicholas-Cheng-De-Fei

Closes #359 

Added images for commands with GUI changes below is the list of commands:
- `view`
- `pin`
- `unpin`
- `toggle`

2024-11-10 08:37 UTC, ITLimJiaWei approved these changes
LGTM

2024-11-11 02:25 UTC, KennethTeo2002 requested changes

2024-11-11 02:25 UTC, KennethTeo2002 commented on docs/UserGuide.md
> +**Result from `find alex david`:**
I think there is a missing line break here.
![image](https://github.com/user-attachments/assets/4755c62f-a197-43f5-ba40-91f3ff3bfdcd)

2024-11-11 09:03 UTC, KennethTeo2002 approved these changes
LGTM

2024-11-11 09:32 UTC, merged