Add delete use case into documentation
AY2425S1-CS2103-F10-3/tp pull request #83
Opened 2024-09-26 05:29 UTC by KennethTeo2002

Closes #82

2024-09-26 05:35 UTC, KennethTeo2002 commented
Code change is between line 291 to 304, the rest were automatic styling change.

2024-09-27 15:53 UTC, sheenkerr requested changes

2024-09-27 15:53 UTC, sheenkerr commented on docs/DeveloperGuide.md
> +2.  Bizbook shows a list of persons.
I think it may be better to use BizBook for all instances of BizBook for a nicer formatting

2024-09-27 15:53 UTC, sheenkerr commented on docs/DeveloperGuide.md
> +1.  User requests to list persons.
I think we can do an inclusion here of the list feature

2024-09-28 14:09 UTC, sheenkerr requested changes

2024-09-28 14:09 UTC, sheenkerr commented on docs/DeveloperGuide.md
> +2.  `Bizbook` shows a list of persons.
I think step 2 can be omitted since we have the inclusion in step 1?

2024-09-28 14:09 UTC, sheenkerr commented on docs/DeveloperGuide.md
> +- 2a. The list is empty.
I think this could be removed? Since we are going to put this extension in the `list` use case?

2024-09-28 14:28 UTC, sheenkerr approved these changes
LGTM

2024-09-30 03:46 UTC, Nicholas-Cheng-De-Fei requested changes

2024-09-30 03:59 UTC, KennethTeo2002 commented on docs/DeveloperGuide.md
I think the response for when the list is empty is handled by the `list persons` use case. As for delete, I would think that the user attempting to delete a person from an empty list is technically index out of bound (aka invalid), thus this extension covers it.

2024-09-30 16:26 UTC, Nicholas-Cheng-De-Fei commented on docs/DeveloperGuide.md
Alright I get where you are coming from.

2024-09-30 16:26 UTC, Nicholas-Cheng-De-Fei approved these changes
LGTM

2024-10-01 02:05 UTC, merged