Add list all contacts use case
AY2425S1-CS2103-F10-3/tp pull request #92
Opened 2024-09-28 14:22 UTC by sheenkerr

2024-09-28 14:33 UTC, joeltio requested changes

2024-09-28 14:33 UTC, joeltio commented on docs/DeveloperGuide.md
> +**Use case: UC2 - List all people saved in `BizBook`**
Any reason why it's UC2 and not UC1?

2024-09-28 14:33 UTC, joeltio commented on docs/DeveloperGuide.md
> +
I think there should be a line about `BizBook` informs user that there are no people in the address book.

2024-09-28 14:33 UTC, joeltio commented on docs/DeveloperGuide.md
> +1.  User requests to list all people saved in their `BizBook`.
Consider adding a "by entering a command" here since it's only later mentioned that this is done through a command in `1b`

2024-09-28 14:35 UTC, joeltio commented on docs/DeveloperGuide.md
> +**Use case: UC2 - List all people saved in `BizBook`**
I realise it's because #89 uses UC1

2024-09-28 14:38 UTC, sheenkerr commented on docs/DeveloperGuide.md
> +**Use case: UC2 - List all people saved in `BizBook`**
Not really, I'll change it to UC1.

2024-09-29 13:06 UTC, ITLimJiaWei requested changes
LGTM pending some minor formatting issues

2024-09-29 13:06 UTC, ITLimJiaWei commented on docs/DeveloperGuide.md
> +      Use case resumes at step 1.
Same as the add contact use case PR, could you remove the indentation to align with Kenneth's format?

2024-09-29 13:06 UTC, ITLimJiaWei commented on docs/DeveloperGuide.md
> +    * Use case ends.
Could change this to just "Use case ends." without the * to be consistent with other use cases.

2024-09-29 14:23 UTC, ITLimJiaWei approved these changes
LGTM

2024-09-29 14:42 UTC, KennethTeo2002 approved these changes
LGTM

2024-10-02 12:28 UTC, joeltio approved these changes
LGTM

2024-10-02 12:28 UTC, merged